%serial data capture and plot
clear all

global s f current_data

current_data = 'COM9';
s = serial(current_data);
set(s,'BaudRate',9600,'DataBits',8,'Parity','none', 'StopBits',1);
s.Terminator = 'CR/LF';

f = figure('Visible','off','Position',[4,4,1366,768]);
%set(f, 'color', [0.1,0.1,0.5]);
set(f, 'color', [0.1,0.1,0.1]);
htext  = uicontrol('Style','text','String','COM Port:',...
         'Position',[50,704,60,15]);
hport = uicontrol('Style','PopupMenu',...
               'Units','normalized',...
               'Position',[0.08 0.93 0.07 0.06],...
               'String','COM1|COM2|COM3|COM4|COM5|COM6|COM7|COM8|COM9|COM10',...
               'Callback',{@selectport_Callback});
hstart = uicontrol('Style','pushbutton','String','Start Connection',...
           'Position',[240,700,100,25],...
           'Callback',{@startbutton_Callback});
hclose = uicontrol('Style','pushbutton','String','Close Connection',...
           'Position',[350,700,100,25],...
           'Callback',{@closebutton_Callback});
hexit = uicontrol('Style','pushbutton','String','Exit',...
           'Position',[460,700,100,25],...
           'Callback',{@exitbutton_Callback});
%align([hstart, hclose, hexit],'Center','None');
       
set(f,'Visible','on');

